namespace KOF.Core.Enums;

internal enum ClassType : int
{
	CLASS_UNKNOWN = -1,

	CLASS_KINDOF_WARRIOR = 1, 
	CLASS_KINDOF_ROGUE = 2,
	CLASS_KINDOF_WIZARD = 3,
	CLASS_KINDOF_PRIEST = 4,
	CLASS_KINDOF_ATTACK_WARRIOR = 5,
	CLASS_KINDOF_DEFEND_WARRIOR = 6,
	CLASS_KINDOF_ARCHER = 7,
	CLASS_KINDOF_ASSASSIN = 8,
	CLASS_KINDOF_ATTACK_WIZARD = 9,
	CLASS_KINDOF_PET_WIZARD = 10,
	CLASS_KINDOF_HEAL_PRIEST = 11,
	CLASS_KINDOF_CURSE_PRIEST = 12,

	CLASS_KA_WARRIOR = 101,
	CLASS_KA_ROGUE = 102,
	CLASS_KA_WIZARD = 103,
	CLASS_KA_PRIEST = 104,
	CLASS_KA_BERSERKER = 105,
	CLASS_KA_GUARDIAN = 106,
	CLASS_KA_HUNTER = 107,
	CLASS_KA_PENETRATOR = 108,
	CLASS_KA_SORCERER = 109,
	CLASS_KA_NECROMANCER = 110,
	CLASS_KA_SHAMAN = 111,
	CLASS_KA_DARKPRIEST = 112,

	CLASS_EL_WARRIOR = 201,
	CLASS_EL_ROGUE = 202,
	CLASS_EL_WIZARD = 203,
	CLASS_EL_PRIEST = 204,
	CLASS_EL_BLADE = 205,
	CLASS_EL_PROTECTOR = 206,
	CLASS_EL_RANGER = 207,
	CLASS_EL_ASSASIN = 208,
	CLASS_EL_MAGE = 209,
	CLASS_EL_ENCHANTER = 210,
	CLASS_EL_CLERIC = 211,
	CLASS_EL_DRUID = 212,

}