namespace KOF.Core.Enums;

public enum ItemAttachPos : int
{
    ITEM_ATTACH_POS_DUAL = 0,
    ITEM_ATTACH_POS_HAND_RIGHT = 1,
    ITEM_ATTACH_POS_HAND_LEFT = 2,
    ITEM_ATTACH_POS_TWOHAND_RIGHT = 3,
    ITEM_ATTACH_POS_TWOHAND_LEFT = 4,
    ITEM_ATTACH_POS_UPPER = 5,
    ITEM_ATTACH_POS_LOWER = 6,
    ITEM_ATTACH_POS_HEAD = 7,
    ITEM_ATTACH_POS_ARM = 8,
    ITEM_ATTACH_POS_FOOT = 9,
    ITEM_ATTACH_POS_EAR = 10,
    ITEM_ATTACH_POS_NECK = 11,
    ITEM_ATTACH_POS_FINGER = 12,
    ITEM_ATTACH_POS_CLOAK = 13,
    ITEM_ATTACH_POS_BELT = 14,
    ITEM_ATTACH_POS_INVENTORY = 15,
}