namespace KOF.Core.Enums;

public enum ItemSlotPos : int
{
    ITEM_SLOT_POS_EAR_RIGHT = 0,
    ITEM_SLOT_POS_HEAD = 1,
    ITEM_SLOT_POS_EAR_LEFT = 2,
    ITEM_SLOT_POS_NECK = 3,
    ITEM_SLOT_POS_UPPER = 4,
    ITEM_SLOT_POS_SHOULDER = 5,
    ITEM_SLOT_POS_HAND_RIGHT = 6,
    ITEM_SLOT_POS_BELT = 7,
    ITEM_SLOT_POS_HAND_LEFT = 8,
    ITEM_SLOT_POS_RING_RIGHT = 9,
    ITEM_SLOT_POS_LOWER = 10,
    ITEM_SLOT_POS_RING_LEFT = 11,
    ITEM_SLOT_POS_GLOVES = 12,
    ITEM_SLOT_POS_SHOES = 13,
}